### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by gusshawstewart** [githubtrainingwithsahar/march-15-caption#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by gusshawstewart** [comment]
hello

**Comment by MichalLeckiExt** [comment]
hey

**Comment by BKPuma** [comment]
Hello!

**Comment by MihaiDia** [comment]
Hello hello

**Comment by lixie888** [comment]
Hello!

**Comment by jbechayda** [comment]
Hello

**Comment by VKolisetty** [comment]
hello

**Comment by mohammadyasub611** [comment]
hello

**Comment by natalialojkoext** [comment]
hello

**Comment by KasiaWM26** [comment]
Hello

**Comment by SCPUMA** [comment]
WASSSUPPPP!?!?!

**Comment by VillaDaniele** [comment]
Hello!

**Comment by CarolineChiari** [comment]
Hi! I left a comment!💪🏻

**Comment by GaborKirschner** [comment]
Hi

**Comment by dschingisab** [comment]
Hola!

**Comment by posoganhorea1983** [comment]
Hello

**Comment by braindead0315** [comment]
Hi

**Comment by blagojevicdoni** [comment]
Hi

**Comment by Jajcarz** [comment]
Hi

**Comment by MartinHaDevPu** [comment]
Hi my comment is woring

**Comment by lmmonge** [comment]
hello world!

**Comment by Antony2111** [comment]
Nice

**Comment by mariancotelea** [comment]
**Hello**

**Comment by aballestero** [comment]
😎

**Comment by BSRV1987** [comment]
@saharM hi

**Comment by mohammadyasub611** [comment]
Hi

**Comment by ak4752** [comment]
wow

**Comment by Jkay34** [comment]
Comment

**Comment by SeySeySey1** [comment]
here

**Comment by bernhardmai** [comment]
hello

**Comment by VillaDaniele** [comment]
Hello all!

**Comment by RainerAM** [comment]
Hello

**Comment by Sli0815** [comment]
commented

**Comment by Sli0815** [comment]
> WASSSUPPPP!?!?!

Whaaaaasssuuuuuuuuuuuuuuuuuuuuuuuuuuup?
